org.gradle.jvmargs=-Xmx2G
org.gradle.configuration-cache=true

# Fabric Properties (https://fabricmc.net/develop)
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Fabric API
fabric_api_version=0.158.0+26.2

# Mod Properties
mod_version=26.2-8-beta.3
maven_group=com.yalu.i18n-support
archives_base_name=Meteor-I18n-Support

# Dependencies
catppuccin_version=2.2.0+mc26.2
